spring:
  application:
    name: activities-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/Activities Service
      database: Activities Service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082



