spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
           - id: userservice
             uri: lb://USERSERVICE
             predicates:
              - Path=/api/users/**

           - id: activities-service
             uri: lb://ACTIVITIES-SERVICE
             predicates:
               - Path=/activities/**

           - id: AI-service
             uri: lb://AI-SERVICE
             predicates:
               - Path=/api/recommendations/**







eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka









server:
  port: 8086