spring:
  application:
    name: AI-Service-Test

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiservice-test
      database: aiservice-test

eureka:
  client:
    enabled: false

server:
  port: 8083

kafka:
  topic:
    name: activity-events-test

logging:
  level:
    root: INFO
    com.Fitness.AI.Service: DEBUG

