spring:
  application:
    name: AI-Service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
     group-id: activity-processor-group
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       spring.json.use.type.headers: false
       spring . json. value. default.type: com.Fitness.AI.Service.model.Activity
       spring.json.trusted.packages : "*"



  data:
    mongodb:
      uri: mongodb://localhost:27017/aiservice
      database: aiservice


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083


kafka:
  topic:
    name: activity-events

