spring:
 application:
  name: userservice

 datasource:
  url: jdbc:postgresql://localhost:5432/FitnessDB_userservice
  username: postgres
  password: 123456


 jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
 port: 8081